data:
  train_files: ${dataset_path}
  val_files: ${dataset_path}

  prompt_key: text          # <- parquet 的列名
  answer_key: id            # <- parquet 的列名（随便填一个存在的列）
  context_key: text         # <- free-form challenger 的语料来源

  image_key: images
  max_prompt_length: 25000
  max_response_length: 4096
  rollout_batch_size: 256
  val_batch_size: 512

  override_chat_template: null
  shuffle: true
  seed: 1

  use_free_form_challenger: true

  # free-form challenger 额外必需字段
  answer_type: "integer"
  max_doc_tokens: 4096
  filter_overlong_prompts: true

  max_pixels: 4194304
  min_pixels: 262144

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  mock_data: test

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 2
    micro_batch_size_per_device_for_experience: 8
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1

    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false

    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw
      lr_warmup_ratio: 0.0

    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true

    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    n: 5
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.65
    enforce_eager: false
    max_num_batched_tokens: 50000
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    limit_images: 0
    val_override_config:
      temperature: 1.0
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: true

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/math.py:compute_score

trainer:
  total_epochs: 2
  max_steps: null
  project_name: SPICE1202-Qwen3-4b-Base
  experiment_name: SPICE1202-Qwen3-4b-Base
  logger: ["console", "swanlab"]
  nnodes: 1
  n_gpus_per_node: 8
  val_freq: 3
  val_before_train: false
  val_only: false
  val_generations_to_log: 3
  save_freq: 5
  save_limit: 3
  save_checkpoint_path: your_checkpoint_path
  load_checkpoint_path: null
